### ISSUE TITLE
Still needed?

### ISSUE THREAD

**Issue by hmijail** [Lej77/move-unloaded-tabs-for-tree-style-tab#7]
Does this add-on still do anything, as of TST 3.9.19 in Firefox 122? 

I have this add-on installed but disabled, and just tried dragging a tree with an unloaded tab to a different window and it stayed unloaded.

**Comment by Lej77** [comment]
This addon changes how tabs are activated/selected in Tree Style Tab's sidebar. Normally they are activated on a mouse down event but if this addon is enabled then they are activated on mouse up and only if the tab wasn't moved.

Without this addon:
![move unloaded tabs - disabled](https://github.com/Lej77/move-unloaded-tabs-for-tree-style-tab/assets/31554212/ae8b36ee-733e-4848-b8da-f77f356ef740)

With this addon:
![move unloaded tabs - enabled](https://github.com/Lej77/move-unloaded-tabs-for-tree-style-tab/assets/31554212/b46d4b96-54f4-42ec-8753-8fa6df9829ea)

(The recordings were made using TST 3.9.19 in Firefox 115.6.0esr, so at least for now this addon is still useful.)
