### ISSUE TITLE
Thanks for this extension

### ISSUE THREAD

**Issue by Rosemyne** [Lej77/move-unloaded-tabs-for-tree-style-tab#9]
Not a support post, feel free to close it, but genuinely, thank you for providing this extension. Was looking into solutions after Firefox decided to load all my tabs specifically in trees in reverse order (and not all the tabs themselves) and this provided an easy way to do it without loading every tab I wanted to move. Thanks again

**Comment by Lej77** [comment]
Your welcome! 

I primarily made this extension because I wanted it myself but I am glad that it is useful to others as well!
